# Check for the target compiler
AC_SUBST([CC], [i686-linux-gnu-gcc])
AC_SUBST([CXX], [i686-linux-gnu-g++])
AC_SUBST([LD], [i686-linux-gnu-ld])
AC_SUBST([AR], [i686-linux-gnu-ar])

AC_SUBST([CC_64], [x86_64-linux-gnu-gcc])
AC_SUBST([CXX_64], [x86_64-linux-gnu-g++])
AC_SUBST([LD_64], [x86_64-linux-gnu-ld])
AC_SUBST([AR_64], [x86_64-linux-gnu-ar])

AC_SUBST([CC_RISCV], [riscv64-linux-gnu-gcc])
AC_SUBST([CXX_RISCV], [riscv64-linux-gnu-g++])
AC_SUBST([LD_RISCV], [riscv64-linux-gnu-ld])
AC_SUBST([AR_RISCV], [riscv64-linux-gnu-ar])

# Wide character support for eCRT (16-bit wchar_t)
AC_SUBST([WCHAR_CFLAGS], [-fshort-wchar])