/**
 * @file display.c
 * @brief Display/Graphics Family Implementation
 *
 * Provides comprehensive GPU and display management supporting:
 * - Modern GPUs: NVIDIA RTX 40/30/20 series, AMD RX 7000/6000 series, Intel Arc
 * - Legacy GPUs: GeForce GTX series, Radeon HD/R series, Intel HD Graphics
 * - Vintage hardware: 3dfx Voodoo, Matrox, S3, ATI Rage/Mach
 * - Display technologies: VGA, DVI, HDMI 2.1, DisplayPort 2.1, eDP, LVDS
 * - VESA BIOS Extensions (VBE) for legacy mode setting
 * - EDID parsing for display identification
 * - Framebuffer management and 2D operations
 *
 * @copyright Copyright (c) 2025 NUX Project
 */

#include <iokit/iokit.h>
#include <iokit/ioservice.h>
#include <iokit/families/display/display.h>
#include <ananke/ntrtl.h>
#include <string.h>
#include <stdio.h>

/**
 * @brief VESA BIOS Extensions (VBE) structures
 */
#define VBE_SIGNATURE               0x4F

typedef struct _VBE_INFO_BLOCK {
    CHAR8   Signature[4];           /**< "VESA" signature */
    UINT16  Version;                /**< VBE version (0x0300 = 3.0) */
    UINT32  OEMStringPtr;           /**< OEM string pointer */
    UINT32  Capabilities;           /**< Capabilities */
    UINT32  VideoModePtr;           /**< Video mode list pointer */
    UINT16  TotalMemory;            /**< Total memory (64KB blocks) */
    UINT16  OEMSoftwareRev;         /**< OEM software revision */
    UINT32  OEMVendorNamePtr;       /**< OEM vendor name pointer */
    UINT32  OEMProductNamePtr;      /**< OEM product name pointer */
    UINT32  OEMProductRevPtr;       /**< OEM product revision pointer */
    UINT8   Reserved[222];          /**< Reserved */
    UINT8   OEMData[256];           /**< OEM data */
} VBE_INFO_BLOCK;

typedef struct _VBE_MODE_INFO {
    UINT16  ModeAttributes;         /**< Mode attributes */
    UINT8   WinAAttributes;         /**< Window A attributes */
    UINT8   WinBAttributes;         /**< Window B attributes */
    UINT16  WinGranularity;         /**< Window granularity */
    UINT16  WinSize;                /**< Window size */
    UINT16  WinASegment;            /**< Window A segment */
    UINT16  WinBSegment;            /**< Window B segment */
    UINT32  WinFuncPtr;             /**< Window function pointer */
    UINT16  BytesPerScanLine;       /**< Bytes per scan line */
    UINT16  XResolution;            /**< X resolution */
    UINT16  YResolution;            /**< Y resolution */
    UINT8   XCharSize;              /**< Character width */
    UINT8   YCharSize;              /**< Character height */
    UINT8   NumberOfPlanes;         /**< Number of planes */
    UINT8   BitsPerPixel;           /**< Bits per pixel */
    UINT8   NumberOfBanks;          /**< Number of banks */
    UINT8   MemoryModel;            /**< Memory model */
    UINT8   BankSize;               /**< Bank size */
    UINT8   NumberOfImagePages;     /**< Number of image pages */
    UINT8   Reserved1;              /**< Reserved */
    UINT8   RedMaskSize;            /**< Red mask size */
    UINT8   RedFieldPosition;       /**< Red field position */
    UINT8   GreenMaskSize;          /**< Green mask size */
    UINT8   GreenFieldPosition;     /**< Green field position */
    UINT8   BlueMaskSize;           /**< Blue mask size */
    UINT8   BlueFieldPosition;      /**< Blue field position */
    UINT8   RsvdMaskSize;           /**< Reserved mask size */
    UINT8   RsvdFieldPosition;      /**< Reserved field position */
    UINT8   DirectColorModeInfo;    /**< Direct color mode info */
    UINT32  PhysBasePtr;            /**< Physical framebuffer address */
    UINT32  Reserved2;              /**< Reserved */
    UINT16  Reserved3;              /**< Reserved */
    UINT8   Reserved4[206];         /**< Reserved */
} VBE_MODE_INFO;

/**
 * @brief Display controller implementation
 */
typedef struct _DISPLAY_CONTROLLER_IMPL {
    IIODisplayController        Vtbl;               /**< Virtual function table */
    IIOService                 *pService;           /**< Underlying service */
    DISPLAY_CONTROLLER_INFO     Info;               /**< Controller information */
    DISPLAY_MODE                CurrentMode;        /**< Current display mode */
    FRAMEBUFFER_INFO            FramebufferInfo;    /**< Framebuffer information */
    VOID                       *pFramebufferVirt;   /**< Mapped framebuffer */
    BOOLEAN                     bInitialized;       /**< Initialization flag */
    UINT32                      uRefCount;          /**< Reference count */
} DISPLAY_CONTROLLER_IMPL;

/**
 * @brief Framebuffer implementation
 */
typedef struct _FRAMEBUFFER_IMPL {
    IIOFramebuffer              Vtbl;               /**< Virtual function table */
    FRAMEBUFFER_INFO            Info;               /**< Framebuffer information */
    VOID                       *pMappedAddress;     /**< Mapped virtual address */
    BOOLEAN                     bMapped;            /**< Mapping flag */
    UINT32                      uRefCount;          /**< Reference count */
} FRAMEBUFFER_IMPL;

/**
 * @brief Comprehensive GPU device database (100+ entries)
 *
 * Covers:
 * - NVIDIA: GeForce (GTX/RTX), Quadro, Tesla, Data Center GPUs
 * - AMD: Radeon (RX/Pro), Instinct, Legacy ATI
 * - Intel: UHD Graphics, Iris, Arc, Data Center
 * - Apple: M1/M2/M3 integrated GPUs
 * - Legacy: 3dfx, Matrox, S3, SiS, VIA
 */
static const GPU_DEVICE_ENTRY g_GPUDatabase[] = {
    // NVIDIA GeForce RTX 40 Series (Ada Lovelace)
    { GPU_VENDOR_NVIDIA, 0x2684, GPU_TYPE_DISCRETE, "NVIDIA GeForce RTX 4090", 24576, VRAM_TYPE_GDDR6X,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_HDR10_PLUS | GPU_CAP_DOLBY_VISION | GPU_CAP_VRR | GPU_CAP_GSYNC |
      GPU_CAP_CUDA | GPU_CAP_RAYTRACING | GPU_CAP_TENSOR_CORES | GPU_CAP_DLSS | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_NVIDIA, 0x2704, GPU_TYPE_DISCRETE, "NVIDIA GeForce RTX 4080", 16384, VRAM_TYPE_GDDR6X,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_VRR | GPU_CAP_GSYNC | GPU_CAP_CUDA | GPU_CAP_RAYTRACING |
      GPU_CAP_TENSOR_CORES | GPU_CAP_DLSS | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_NVIDIA, 0x2782, GPU_TYPE_DISCRETE, "NVIDIA GeForce RTX 4070 Ti", 12288, VRAM_TYPE_GDDR6X,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_VRR | GPU_CAP_GSYNC | GPU_CAP_CUDA | GPU_CAP_RAYTRACING |
      GPU_CAP_TENSOR_CORES | GPU_CAP_DLSS | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_NVIDIA, 0x2786, GPU_TYPE_DISCRETE, "NVIDIA GeForce RTX 4070", 12288, VRAM_TYPE_GDDR6X,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_VRR | GPU_CAP_GSYNC | GPU_CAP_CUDA | GPU_CAP_RAYTRACING |
      GPU_CAP_TENSOR_CORES | GPU_CAP_DLSS | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_NVIDIA, 0x2803, GPU_TYPE_DISCRETE, "NVIDIA GeForce RTX 4060 Ti", 8192, VRAM_TYPE_GDDR6,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_VRR | GPU_CAP_GSYNC | GPU_CAP_CUDA | GPU_CAP_RAYTRACING |
      GPU_CAP_TENSOR_CORES | GPU_CAP_DLSS | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },

    // NVIDIA GeForce RTX 30 Series (Ampere)
    { GPU_VENDOR_NVIDIA, 0x2204, GPU_TYPE_DISCRETE, "NVIDIA GeForce RTX 3090", 24576, VRAM_TYPE_GDDR6X,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_VRR | GPU_CAP_GSYNC | GPU_CAP_CUDA | GPU_CAP_RAYTRACING |
      GPU_CAP_TENSOR_CORES | GPU_CAP_DLSS | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_NVIDIA, 0x2206, GPU_TYPE_DISCRETE, "NVIDIA GeForce RTX 3080", 10240, VRAM_TYPE_GDDR6X,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_VRR | GPU_CAP_GSYNC | GPU_CAP_CUDA | GPU_CAP_RAYTRACING |
      GPU_CAP_TENSOR_CORES | GPU_CAP_DLSS | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_NVIDIA, 0x2484, GPU_TYPE_DISCRETE, "NVIDIA GeForce RTX 3070", 8192, VRAM_TYPE_GDDR6,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_VRR | GPU_CAP_GSYNC | GPU_CAP_CUDA | GPU_CAP_RAYTRACING |
      GPU_CAP_TENSOR_CORES | GPU_CAP_DLSS | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_NVIDIA, 0x2489, GPU_TYPE_DISCRETE, "NVIDIA GeForce RTX 3060 Ti", 8192, VRAM_TYPE_GDDR6,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_VRR | GPU_CAP_GSYNC | GPU_CAP_CUDA | GPU_CAP_RAYTRACING |
      GPU_CAP_TENSOR_CORES | GPU_CAP_DLSS | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },

    // NVIDIA GeForce RTX 20 Series (Turing)
    { GPU_VENDOR_NVIDIA, 0x1E04, GPU_TYPE_DISCRETE, "NVIDIA GeForce RTX 2080 Ti", 11264, VRAM_TYPE_GDDR6,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_VRR | GPU_CAP_GSYNC | GPU_CAP_CUDA | GPU_CAP_RAYTRACING |
      GPU_CAP_TENSOR_CORES | GPU_CAP_DLSS | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_NVIDIA, 0x1E07, GPU_TYPE_DISCRETE, "NVIDIA GeForce RTX 2080", 8192, VRAM_TYPE_GDDR6,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_VRR | GPU_CAP_GSYNC | GPU_CAP_CUDA | GPU_CAP_RAYTRACING |
      GPU_CAP_TENSOR_CORES | GPU_CAP_DLSS | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_NVIDIA, 0x1F02, GPU_TYPE_DISCRETE, "NVIDIA GeForce RTX 2070", 8192, VRAM_TYPE_GDDR6,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_VRR | GPU_CAP_GSYNC | GPU_CAP_CUDA | GPU_CAP_RAYTRACING |
      GPU_CAP_TENSOR_CORES | GPU_CAP_DLSS | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_NVIDIA, 0x1F06, GPU_TYPE_DISCRETE, "NVIDIA GeForce RTX 2060", 6144, VRAM_TYPE_GDDR6,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_VRR | GPU_CAP_GSYNC | GPU_CAP_CUDA | GPU_CAP_RAYTRACING |
      GPU_CAP_TENSOR_CORES | GPU_CAP_DLSS | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },

    // NVIDIA GeForce GTX 16 Series (Turing without RT)
    { GPU_VENDOR_NVIDIA, 0x2182, GPU_TYPE_DISCRETE, "NVIDIA GeForce GTX 1660 Ti", 6144, VRAM_TYPE_GDDR6,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_VRR | GPU_CAP_GSYNC | GPU_CAP_CUDA | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_NVIDIA, 0x2184, GPU_TYPE_DISCRETE, "NVIDIA GeForce GTX 1660", 6144, VRAM_TYPE_GDDR5,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_VRR | GPU_CAP_GSYNC | GPU_CAP_CUDA | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_NVIDIA, 0x2187, GPU_TYPE_DISCRETE, "NVIDIA GeForce GTX 1650", 4096, VRAM_TYPE_GDDR5,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_VRR | GPU_CAP_CUDA | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },

    // NVIDIA GeForce GTX 10 Series (Pascal)
    { GPU_VENDOR_NVIDIA, 0x1B06, GPU_TYPE_DISCRETE, "NVIDIA GeForce GTX 1080 Ti", 11264, VRAM_TYPE_GDDR5X,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_VRR | GPU_CAP_GSYNC | GPU_CAP_CUDA | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_NVIDIA, 0x1B80, GPU_TYPE_DISCRETE, "NVIDIA GeForce GTX 1080", 8192, VRAM_TYPE_GDDR5X,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_VRR | GPU_CAP_GSYNC | GPU_CAP_CUDA | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_NVIDIA, 0x1B81, GPU_TYPE_DISCRETE, "NVIDIA GeForce GTX 1070", 8192, VRAM_TYPE_GDDR5,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_VRR | GPU_CAP_GSYNC | GPU_CAP_CUDA | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_NVIDIA, 0x1C03, GPU_TYPE_DISCRETE, "NVIDIA GeForce GTX 1060", 6144, VRAM_TYPE_GDDR5,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_VRR | GPU_CAP_GSYNC | GPU_CAP_CUDA | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_NVIDIA, 0x1C81, GPU_TYPE_DISCRETE, "NVIDIA GeForce GTX 1050 Ti", 4096, VRAM_TYPE_GDDR5,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_MULTI_MONITOR |
      GPU_CAP_CUDA | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },

    // NVIDIA Quadro (Professional)
    { GPU_VENDOR_NVIDIA, 0x2230, GPU_TYPE_DISCRETE, "NVIDIA RTX A6000", 48 * 1024, VRAM_TYPE_GDDR6,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_VRR | GPU_CAP_CUDA | GPU_CAP_RAYTRACING | GPU_CAP_TENSOR_CORES |
      GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_NVIDIA, 0x2231, GPU_TYPE_DISCRETE, "NVIDIA RTX A5000", 24576, VRAM_TYPE_GDDR6,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_CUDA | GPU_CAP_RAYTRACING | GPU_CAP_TENSOR_CORES |
      GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },

    // NVIDIA Tesla/Data Center (Ampere/Hopper)
    { GPU_VENDOR_NVIDIA, 0x20B0, GPU_TYPE_DISCRETE, "NVIDIA A100 PCIe", 40960, VRAM_TYPE_HBM2E,
      GPU_CAP_VIDEO_DECODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_CUDA | GPU_CAP_TENSOR_CORES },
    { GPU_VENDOR_NVIDIA, 0x2330, GPU_TYPE_DISCRETE, "NVIDIA H100 PCIe", 80 * 1024, VRAM_TYPE_HBM3,
      GPU_CAP_VIDEO_DECODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 | GPU_CAP_CUDA | GPU_CAP_TENSOR_CORES },
    { GPU_VENDOR_NVIDIA, 0x1DB4, GPU_TYPE_DISCRETE, "NVIDIA Tesla V100 PCIe", 16384, VRAM_TYPE_HBM2,
      GPU_CAP_VIDEO_DECODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_CUDA | GPU_CAP_TENSOR_CORES },

    // AMD Radeon RX 7000 Series (RDNA 3)
    { GPU_VENDOR_AMD, 0x744C, GPU_TYPE_DISCRETE, "AMD Radeon RX 7900 XTX", 24576, VRAM_TYPE_GDDR6,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_HDR10_PLUS | GPU_CAP_VRR | GPU_CAP_FREESYNC | GPU_CAP_OPENCL |
      GPU_CAP_ROCM | GPU_CAP_RAYTRACING | GPU_CAP_FSR | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT | GPU_CAP_USB_C_DP },
    { GPU_VENDOR_AMD, 0x7448, GPU_TYPE_DISCRETE, "AMD Radeon RX 7900 XT", 20480, VRAM_TYPE_GDDR6,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_VRR | GPU_CAP_FREESYNC | GPU_CAP_OPENCL | GPU_CAP_ROCM |
      GPU_CAP_RAYTRACING | GPU_CAP_FSR | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_AMD, 0x747E, GPU_TYPE_DISCRETE, "AMD Radeon RX 7800 XT", 16384, VRAM_TYPE_GDDR6,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_VRR | GPU_CAP_FREESYNC | GPU_CAP_OPENCL | GPU_CAP_ROCM |
      GPU_CAP_RAYTRACING | GPU_CAP_FSR | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_AMD, 0x7480, GPU_TYPE_DISCRETE, "AMD Radeon RX 7700 XT", 12288, VRAM_TYPE_GDDR6,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_VRR | GPU_CAP_FREESYNC | GPU_CAP_OPENCL | GPU_CAP_ROCM |
      GPU_CAP_RAYTRACING | GPU_CAP_FSR | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_AMD, 0x7489, GPU_TYPE_DISCRETE, "AMD Radeon RX 7600", 8192, VRAM_TYPE_GDDR6,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_VRR | GPU_CAP_FREESYNC | GPU_CAP_OPENCL | GPU_CAP_ROCM |
      GPU_CAP_RAYTRACING | GPU_CAP_FSR | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },

    // AMD Radeon RX 6000 Series (RDNA 2)
    { GPU_VENDOR_AMD, 0x73BF, GPU_TYPE_DISCRETE, "AMD Radeon RX 6900 XT", 16384, VRAM_TYPE_GDDR6,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_VRR | GPU_CAP_FREESYNC | GPU_CAP_OPENCL | GPU_CAP_ROCM |
      GPU_CAP_RAYTRACING | GPU_CAP_FSR | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_AMD, 0x73DF, GPU_TYPE_DISCRETE, "AMD Radeon RX 6800 XT", 16384, VRAM_TYPE_GDDR6,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_VRR | GPU_CAP_FREESYNC | GPU_CAP_OPENCL | GPU_CAP_ROCM |
      GPU_CAP_RAYTRACING | GPU_CAP_FSR | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_AMD, 0x73FF, GPU_TYPE_DISCRETE, "AMD Radeon RX 6700 XT", 12288, VRAM_TYPE_GDDR6,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_VRR | GPU_CAP_FREESYNC | GPU_CAP_OPENCL | GPU_CAP_ROCM |
      GPU_CAP_RAYTRACING | GPU_CAP_FSR | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_AMD, 0x73EF, GPU_TYPE_DISCRETE, "AMD Radeon RX 6650 XT", 8192, VRAM_TYPE_GDDR6,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_VRR | GPU_CAP_FREESYNC | GPU_CAP_OPENCL | GPU_CAP_ROCM |
      GPU_CAP_RAYTRACING | GPU_CAP_FSR | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_AMD, 0x73FF, GPU_TYPE_DISCRETE, "AMD Radeon RX 6600 XT", 8192, VRAM_TYPE_GDDR6,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_VRR | GPU_CAP_FREESYNC | GPU_CAP_OPENCL | GPU_CAP_ROCM |
      GPU_CAP_RAYTRACING | GPU_CAP_FSR | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },

    // AMD Radeon RX 5000 Series (RDNA)
    { GPU_VENDOR_AMD, 0x731F, GPU_TYPE_DISCRETE, "AMD Radeon RX 5700 XT", 8192, VRAM_TYPE_GDDR6,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_VRR | GPU_CAP_FREESYNC | GPU_CAP_OPENCL | GPU_CAP_ROCM |
      GPU_CAP_FSR | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_AMD, 0x7340, GPU_TYPE_DISCRETE, "AMD Radeon RX 5700", 8192, VRAM_TYPE_GDDR6,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_VRR | GPU_CAP_FREESYNC | GPU_CAP_OPENCL | GPU_CAP_ROCM |
      GPU_CAP_FSR | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_AMD, 0x7360, GPU_TYPE_DISCRETE, "AMD Radeon RX 5600 XT", 6144, VRAM_TYPE_GDDR6,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_VRR | GPU_CAP_FREESYNC | GPU_CAP_OPENCL | GPU_CAP_ROCM |
      GPU_CAP_FSR | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },

    // AMD Radeon Vega Series
    { GPU_VENDOR_AMD, 0x687F, GPU_TYPE_DISCRETE, "AMD Radeon RX Vega 64", 8192, VRAM_TYPE_HBM2,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_VRR | GPU_CAP_FREESYNC | GPU_CAP_OPENCL | GPU_CAP_ROCM |
      GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_AMD, 0x66AF, GPU_TYPE_DISCRETE, "AMD Radeon VII", 16384, VRAM_TYPE_HBM2,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_VRR | GPU_CAP_FREESYNC | GPU_CAP_OPENCL | GPU_CAP_ROCM |
      GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },

    // AMD Radeon Pro
    { GPU_VENDOR_AMD, 0x73A1, GPU_TYPE_DISCRETE, "AMD Radeon PRO W6800", 32 * 1024, VRAM_TYPE_GDDR6,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_OPENCL | GPU_CAP_ROCM | GPU_CAP_RAYTRACING |
      GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },

    // AMD Instinct (Data Center)
    { GPU_VENDOR_AMD, 0x740F, GPU_TYPE_DISCRETE, "AMD Instinct MI300X", 192 * 1024, VRAM_TYPE_HBM3,
      GPU_CAP_VIDEO_DECODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 | GPU_CAP_OPENCL | GPU_CAP_ROCM },
    { GPU_VENDOR_AMD, 0x738C, GPU_TYPE_DISCRETE, "AMD Instinct MI250X", 128 * 1024, VRAM_TYPE_HBM2E,
      GPU_CAP_VIDEO_DECODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_OPENCL | GPU_CAP_ROCM },
    { GPU_VENDOR_AMD, 0x738E, GPU_TYPE_DISCRETE, "AMD Instinct MI210", 64 * 1024, VRAM_TYPE_HBM2E,
      GPU_CAP_VIDEO_DECODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_OPENCL | GPU_CAP_ROCM },
    { GPU_VENDOR_AMD, 0x7408, GPU_TYPE_DISCRETE, "AMD Instinct MI100", 32 * 1024, VRAM_TYPE_HBM2,
      GPU_CAP_VIDEO_DECODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_OPENCL | GPU_CAP_ROCM },

    // Intel Arc (Alchemist)
    { GPU_VENDOR_INTEL, 0x56A0, GPU_TYPE_DISCRETE, "Intel Arc A770", 16384, VRAM_TYPE_GDDR6,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 | GPU_CAP_VP9 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_VRR | GPU_CAP_OPENCL | GPU_CAP_ONEAPI | GPU_CAP_RAYTRACING |
      GPU_CAP_XESS | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_INTEL, 0x56A5, GPU_TYPE_DISCRETE, "Intel Arc A750", 8192, VRAM_TYPE_GDDR6,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 | GPU_CAP_VP9 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_VRR | GPU_CAP_OPENCL | GPU_CAP_ONEAPI | GPU_CAP_RAYTRACING |
      GPU_CAP_XESS | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_INTEL, 0x5690, GPU_TYPE_DISCRETE, "Intel Arc A580", 8192, VRAM_TYPE_GDDR6,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 | GPU_CAP_VP9 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_VRR | GPU_CAP_OPENCL | GPU_CAP_ONEAPI | GPU_CAP_RAYTRACING |
      GPU_CAP_XESS | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_INTEL, 0x56A1, GPU_TYPE_DISCRETE, "Intel Arc A380", 6144, VRAM_TYPE_GDDR6,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 | GPU_CAP_VP9 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_VRR | GPU_CAP_OPENCL | GPU_CAP_ONEAPI | GPU_CAP_RAYTRACING |
      GPU_CAP_XESS | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },

    // Intel UHD Graphics (Integrated - Alder Lake/Raptor Lake)
    { GPU_VENDOR_INTEL, 0x4680, GPU_TYPE_INTEGRATED, "Intel UHD Graphics 770", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_OPENCL | GPU_CAP_ONEAPI | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_INTEL, 0x4690, GPU_TYPE_INTEGRATED, "Intel UHD Graphics 730", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_OPENCL | GPU_CAP_ONEAPI | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },

    // Intel Iris Xe Graphics (Integrated - Tiger Lake/Alder Lake)
    { GPU_VENDOR_INTEL, 0x9A49, GPU_TYPE_INTEGRATED, "Intel Iris Xe Graphics", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_OPENCL | GPU_CAP_ONEAPI | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_INTEL, 0x9A40, GPU_TYPE_INTEGRATED, "Intel Iris Xe Graphics (i7)", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_OPENCL | GPU_CAP_ONEAPI | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },

    // Intel HD Graphics (Integrated - older generations)
    { GPU_VENDOR_INTEL, 0x0412, GPU_TYPE_INTEGRATED, "Intel HD Graphics 4600", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_H264 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_OPENCL | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_INTEL, 0x0416, GPU_TYPE_INTEGRATED, "Intel HD Graphics 4600 (Mobile)", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_H264 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_OPENCL | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_INTEL, 0x0A16, GPU_TYPE_INTEGRATED, "Intel HD Graphics (Haswell)", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_H264 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_OPENCL | GPU_CAP_HDMI_OUTPUT | GPU_CAP_VGA_OUTPUT | GPU_CAP_DVI_OUTPUT },
    { GPU_VENDOR_INTEL, 0x0166, GPU_TYPE_INTEGRATED, "Intel HD Graphics 4000", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_H264 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_OPENCL | GPU_CAP_HDMI_OUTPUT | GPU_CAP_VGA_OUTPUT | GPU_CAP_DVI_OUTPUT },

    // Intel Data Center GPU
    { GPU_VENDOR_INTEL, 0x0BD5, GPU_TYPE_DISCRETE, "Intel Data Center GPU Max 1550", 128 * 1024, VRAM_TYPE_HBM2E,
      GPU_CAP_VIDEO_DECODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 | GPU_CAP_OPENCL | GPU_CAP_ONEAPI | GPU_CAP_RAYTRACING },

    // Apple Silicon (Integrated)
    { GPU_VENDOR_APPLE, 0x0001, GPU_TYPE_INTEGRATED, "Apple M1 GPU (7-core)", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT | GPU_CAP_THUNDERBOLT },
    { GPU_VENDOR_APPLE, 0x0002, GPU_TYPE_INTEGRATED, "Apple M1 GPU (8-core)", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT | GPU_CAP_THUNDERBOLT },
    { GPU_VENDOR_APPLE, 0x0010, GPU_TYPE_INTEGRATED, "Apple M1 Pro GPU", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT | GPU_CAP_THUNDERBOLT },
    { GPU_VENDOR_APPLE, 0x0011, GPU_TYPE_INTEGRATED, "Apple M1 Max GPU", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT | GPU_CAP_THUNDERBOLT },
    { GPU_VENDOR_APPLE, 0x0012, GPU_TYPE_INTEGRATED, "Apple M1 Ultra GPU", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT | GPU_CAP_THUNDERBOLT },
    { GPU_VENDOR_APPLE, 0x0020, GPU_TYPE_INTEGRATED, "Apple M2 GPU", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT | GPU_CAP_THUNDERBOLT },
    { GPU_VENDOR_APPLE, 0x0021, GPU_TYPE_INTEGRATED, "Apple M2 Pro GPU", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT | GPU_CAP_THUNDERBOLT },
    { GPU_VENDOR_APPLE, 0x0022, GPU_TYPE_INTEGRATED, "Apple M2 Max GPU", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT | GPU_CAP_THUNDERBOLT },
    { GPU_VENDOR_APPLE, 0x0030, GPU_TYPE_INTEGRATED, "Apple M3 GPU", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_RAYTRACING | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT | GPU_CAP_THUNDERBOLT },
    { GPU_VENDOR_APPLE, 0x0031, GPU_TYPE_INTEGRATED, "Apple M3 Pro GPU", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_RAYTRACING | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT | GPU_CAP_THUNDERBOLT },
    { GPU_VENDOR_APPLE, 0x0032, GPU_TYPE_INTEGRATED, "Apple M3 Max GPU", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_HDR10 | GPU_CAP_RAYTRACING | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT | GPU_CAP_THUNDERBOLT },

    // Legacy ATI Radeon (pre-AMD era)
    { GPU_VENDOR_AMD, 0x5E4B, GPU_TYPE_DISCRETE, "ATI Radeon X1950 XTX", 512, VRAM_TYPE_GDDR4,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_MULTI_MONITOR |
      GPU_CAP_VGA_OUTPUT | GPU_CAP_DVI_OUTPUT },
    { GPU_VENDOR_AMD, 0x9400, GPU_TYPE_DISCRETE, "ATI Radeon HD 2900 XT", 1024, VRAM_TYPE_GDDR4,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_H264 | GPU_CAP_MULTI_MONITOR |
      GPU_CAP_VGA_OUTPUT | GPU_CAP_DVI_OUTPUT | GPU_CAP_HDMI_OUTPUT },
    { GPU_VENDOR_AMD, 0x4C57, GPU_TYPE_DISCRETE, "ATI Rage 128 GL", 32, VRAM_TYPE_SDRAM,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VGA_OUTPUT },

    // Legacy NVIDIA (pre-GeForce)
    { GPU_VENDOR_NVIDIA, 0x0020, GPU_TYPE_DISCRETE, "NVIDIA Riva TNT", 16, VRAM_TYPE_SDRAM,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VGA_OUTPUT },
    { GPU_VENDOR_NVIDIA, 0x0028, GPU_TYPE_DISCRETE, "NVIDIA Riva TNT2", 32, VRAM_TYPE_SDRAM,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VGA_OUTPUT },

    // 3dfx (legendary Voodoo series)
    { GPU_VENDOR_3DFX, 0x0001, GPU_TYPE_DISCRETE, "3dfx Voodoo Graphics", 4, VRAM_TYPE_SDRAM,
      GPU_CAP_3D_ACCEL | GPU_CAP_VGA_OUTPUT },
    { GPU_VENDOR_3DFX, 0x0002, GPU_TYPE_DISCRETE, "3dfx Voodoo2", 12, VRAM_TYPE_SDRAM,
      GPU_CAP_3D_ACCEL | GPU_CAP_VGA_OUTPUT },
    { GPU_VENDOR_3DFX, 0x0003, GPU_TYPE_DISCRETE, "3dfx Voodoo Banshee", 16, VRAM_TYPE_SDRAM,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VGA_OUTPUT },
    { GPU_VENDOR_3DFX, 0x0005, GPU_TYPE_DISCRETE, "3dfx Voodoo3", 16, VRAM_TYPE_SDRAM,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VGA_OUTPUT },
    { GPU_VENDOR_3DFX, 0x0009, GPU_TYPE_DISCRETE, "3dfx Voodoo5", 64, VRAM_TYPE_SDRAM,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VGA_OUTPUT },

    // Matrox
    { GPU_VENDOR_MATROX, 0x0519, GPU_TYPE_DISCRETE, "Matrox Millennium G200", 16, VRAM_TYPE_SDRAM,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_MULTI_MONITOR | GPU_CAP_VGA_OUTPUT },
    { GPU_VENDOR_MATROX, 0x0525, GPU_TYPE_DISCRETE, "Matrox Millennium G400", 32, VRAM_TYPE_SDRAM,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_MULTI_MONITOR | GPU_CAP_VGA_OUTPUT | GPU_CAP_DVI_OUTPUT },
    { GPU_VENDOR_MATROX, 0x2527, GPU_TYPE_DISCRETE, "Matrox Millennium G550", 32, VRAM_TYPE_DDR,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_MULTI_MONITOR | GPU_CAP_VGA_OUTPUT | GPU_CAP_DVI_OUTPUT },

    // S3 Graphics
    { GPU_VENDOR_S3, 0x5631, GPU_TYPE_DISCRETE, "S3 Trio 64V+", 4, VRAM_TYPE_SDRAM,
      GPU_CAP_2D_ACCEL | GPU_CAP_VGA_OUTPUT },
    { GPU_VENDOR_S3, 0x8A01, GPU_TYPE_DISCRETE, "S3 Savage 4", 32, VRAM_TYPE_SDRAM,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VGA_OUTPUT },
    { GPU_VENDOR_S3, 0x8A10, GPU_TYPE_DISCRETE, "S3 Savage 2000", 64, VRAM_TYPE_SDRAM,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VGA_OUTPUT | GPU_CAP_DVI_OUTPUT },

    // VIA/S3 Chrome
    { GPU_VENDOR_VIA, 0x3108, GPU_TYPE_INTEGRATED, "VIA Chrome9 HC3", 0, VRAM_TYPE_DDR2,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VGA_OUTPUT | GPU_CAP_DVI_OUTPUT },

    // SiS
    { GPU_VENDOR_SIS, 0x6326, GPU_TYPE_INTEGRATED, "SiS 6326", 0, VRAM_TYPE_SDRAM,
      GPU_CAP_2D_ACCEL | GPU_CAP_VGA_OUTPUT },
    { GPU_VENDOR_SIS, 0x0315, GPU_TYPE_INTEGRATED, "SiS 315", 0, VRAM_TYPE_DDR,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VGA_OUTPUT | GPU_CAP_DVI_OUTPUT },

    // Virtual GPUs
    { GPU_VENDOR_VMWARE, 0x0405, GPU_TYPE_VIRTUAL, "VMware SVGA II", 128, VRAM_TYPE_SDRAM,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VGA_OUTPUT },
    { GPU_VENDOR_QEMU, 0x1111, GPU_TYPE_VIRTUAL, "QEMU VGA", 16, VRAM_TYPE_SDRAM,
      GPU_CAP_2D_ACCEL | GPU_CAP_VGA_OUTPUT },
    { GPU_VENDOR_VMWARE, 0x0406, GPU_TYPE_VIRTUAL, "VMware SVGA 3", 256, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },

    // ARM Mali GPUs (Mobile/Embedded)
    { GPU_VENDOR_ARM, 0x6000, GPU_TYPE_INTEGRATED, "ARM Mali-G610", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 |
      GPU_CAP_OPENCL | GPU_CAP_HDMI_OUTPUT },
    { GPU_VENDOR_ARM, 0x6001, GPU_TYPE_INTEGRATED, "ARM Mali-G710", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 |
      GPU_CAP_OPENCL | GPU_CAP_RAYTRACING | GPU_CAP_HDMI_OUTPUT },
    { GPU_VENDOR_ARM, 0x7000, GPU_TYPE_INTEGRATED, "ARM Mali-G78", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 |
      GPU_CAP_OPENCL | GPU_CAP_HDMI_OUTPUT },
    { GPU_VENDOR_ARM, 0x7001, GPU_TYPE_INTEGRATED, "ARM Mali-G77", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 |
      GPU_CAP_OPENCL | GPU_CAP_HDMI_OUTPUT },
    { GPU_VENDOR_ARM, 0x7002, GPU_TYPE_INTEGRATED, "ARM Mali-G76", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 |
      GPU_CAP_OPENCL | GPU_CAP_HDMI_OUTPUT },
    { GPU_VENDOR_ARM, 0x7003, GPU_TYPE_INTEGRATED, "ARM Mali-G57", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_OPENCL },
    { GPU_VENDOR_ARM, 0x7004, GPU_TYPE_INTEGRATED, "ARM Mali-G52", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_OPENCL },
    { GPU_VENDOR_ARM, 0x7005, GPU_TYPE_INTEGRATED, "ARM Mali-G51", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_H264 | GPU_CAP_OPENCL },

    // Qualcomm Adreno (Mobile)
    { GPU_VENDOR_QUALCOMM, 0x7000, GPU_TYPE_INTEGRATED, "Qualcomm Adreno 740", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 |
      GPU_CAP_OPENCL | GPU_CAP_RAYTRACING | GPU_CAP_HDMI_OUTPUT },
    { GPU_VENDOR_QUALCOMM, 0x7001, GPU_TYPE_INTEGRATED, "Qualcomm Adreno 730", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 |
      GPU_CAP_OPENCL | GPU_CAP_RAYTRACING | GPU_CAP_HDMI_OUTPUT },
    { GPU_VENDOR_QUALCOMM, 0x7002, GPU_TYPE_INTEGRATED, "Qualcomm Adreno 720", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 |
      GPU_CAP_OPENCL | GPU_CAP_HDMI_OUTPUT },
    { GPU_VENDOR_QUALCOMM, 0x7003, GPU_TYPE_INTEGRATED, "Qualcomm Adreno 710", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 |
      GPU_CAP_OPENCL | GPU_CAP_HDMI_OUTPUT },
    { GPU_VENDOR_QUALCOMM, 0x6000, GPU_TYPE_INTEGRATED, "Qualcomm Adreno 650", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 |
      GPU_CAP_OPENCL | GPU_CAP_HDMI_OUTPUT },
    { GPU_VENDOR_QUALCOMM, 0x6001, GPU_TYPE_INTEGRATED, "Qualcomm Adreno 640", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 |
      GPU_CAP_OPENCL | GPU_CAP_HDMI_OUTPUT },
    { GPU_VENDOR_QUALCOMM, 0x6002, GPU_TYPE_INTEGRATED, "Qualcomm Adreno 630", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 |
      GPU_CAP_OPENCL | GPU_CAP_HDMI_OUTPUT },

    // PowerVR (Imagination Technologies)
    { GPU_VENDOR_POWERVR, 0x9000, GPU_TYPE_INTEGRATED, "PowerVR GT7900", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_H264 | GPU_CAP_OPENCL },
    { GPU_VENDOR_POWERVR, 0x9001, GPU_TYPE_INTEGRATED, "PowerVR GX6650", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_H264 | GPU_CAP_OPENCL },
    { GPU_VENDOR_POWERVR, 0x9002, GPU_TYPE_INTEGRATED, "PowerVR G6430", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_H264 | GPU_CAP_OPENCL },

    // More Intel Arc variants
    { GPU_VENDOR_INTEL, 0x4905, GPU_TYPE_DISCRETE, "Intel Arc A310", 4096, VRAM_TYPE_GDDR6,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 | GPU_CAP_AV1 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_OPENCL | GPU_CAP_ONEAPI | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },

    // More NVIDIA GeForce (older)
    { GPU_VENDOR_NVIDIA, 0x1180, GPU_TYPE_DISCRETE, "NVIDIA GeForce GTX 680", 2048, VRAM_TYPE_GDDR5,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_H264 | GPU_CAP_MULTI_MONITOR | GPU_CAP_CUDA |
      GPU_CAP_VGA_OUTPUT | GPU_CAP_DVI_OUTPUT | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_NVIDIA, 0x1004, GPU_TYPE_DISCRETE, "NVIDIA GeForce GTX 780", 3072, VRAM_TYPE_GDDR5,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_H264 | GPU_CAP_MULTI_MONITOR | GPU_CAP_CUDA |
      GPU_CAP_DVI_OUTPUT | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_NVIDIA, 0x1380, GPU_TYPE_DISCRETE, "NVIDIA GeForce GTX 750 Ti", 2048, VRAM_TYPE_GDDR5,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_H264 | GPU_CAP_MULTI_MONITOR | GPU_CAP_CUDA |
      GPU_CAP_DVI_OUTPUT | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },

    // More AMD Radeon (older)
    { GPU_VENDOR_AMD, 0x67DF, GPU_TYPE_DISCRETE, "AMD Radeon RX 480", 8192, VRAM_TYPE_GDDR5,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_VRR | GPU_CAP_FREESYNC | GPU_CAP_OPENCL | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_AMD, 0x67EF, GPU_TYPE_DISCRETE, "AMD Radeon RX 470", 4096, VRAM_TYPE_GDDR5,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_VIDEO_ENCODE | GPU_CAP_H264 | GPU_CAP_H265 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_VRR | GPU_CAP_FREESYNC | GPU_CAP_OPENCL | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_AMD, 0x67FF, GPU_TYPE_DISCRETE, "AMD Radeon RX 460", 2048, VRAM_TYPE_GDDR5,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_H264 | GPU_CAP_H265 |
      GPU_CAP_MULTI_MONITOR | GPU_CAP_VRR | GPU_CAP_FREESYNC | GPU_CAP_OPENCL | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_AMD, 0x6810, GPU_TYPE_DISCRETE, "AMD Radeon R9 290X", 4096, VRAM_TYPE_GDDR5,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_H264 | GPU_CAP_MULTI_MONITOR | GPU_CAP_FREESYNC |
      GPU_CAP_OPENCL | GPU_CAP_VGA_OUTPUT | GPU_CAP_DVI_OUTPUT | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_AMD, 0x6818, GPU_TYPE_DISCRETE, "AMD Radeon R9 290", 4096, VRAM_TYPE_GDDR5,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_H264 | GPU_CAP_MULTI_MONITOR | GPU_CAP_FREESYNC |
      GPU_CAP_OPENCL | GPU_CAP_VGA_OUTPUT | GPU_CAP_DVI_OUTPUT | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },
    { GPU_VENDOR_AMD, 0x67B0, GPU_TYPE_DISCRETE, "AMD Radeon R9 390", 8192, VRAM_TYPE_GDDR5,
      GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_H264 | GPU_CAP_MULTI_MONITOR | GPU_CAP_FREESYNC |
      GPU_CAP_OPENCL | GPU_CAP_DVI_OUTPUT | GPU_CAP_HDMI_OUTPUT | GPU_CAP_DP_OUTPUT },

    // More Intel HD Graphics
    { GPU_VENDOR_INTEL, 0x0102, GPU_TYPE_INTEGRATED, "Intel HD Graphics 2000", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_H264 | GPU_CAP_VGA_OUTPUT | GPU_CAP_DVI_OUTPUT },
    { GPU_VENDOR_INTEL, 0x0112, GPU_TYPE_INTEGRATED, "Intel HD Graphics 3000", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_H264 | GPU_CAP_OPENCL |
      GPU_CAP_VGA_OUTPUT | GPU_CAP_DVI_OUTPUT | GPU_CAP_HDMI_OUTPUT },
    { GPU_VENDOR_INTEL, 0x0152, GPU_TYPE_INTEGRATED, "Intel HD Graphics 2500", 0, VRAM_TYPE_DDR3,
      GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_VIDEO_DECODE | GPU_CAP_H264 | GPU_CAP_OPENCL |
      GPU_CAP_VGA_OUTPUT | GPU_CAP_DVI_OUTPUT | GPU_CAP_HDMI_OUTPUT },
};

static const UINT32 g_GPUDatabaseCount = sizeof(g_GPUDatabase) / sizeof(GPU_DEVICE_ENTRY);

/**
 * @brief Global display subsystem state
 */
static struct {
    BOOLEAN     bInitialized;
    UINT32      uControllerCount;
} g_DisplaySubsystem = { FALSE, 0 };

/**
 * @brief Standard display modes database
 */
static const DISPLAY_MODE g_StandardModes[] = {
    // VGA/SVGA modes
    { 640, 480, 60, 8, PIXEL_FORMAT_RGB888, COLOR_SPACE_SRGB, FALSE, FALSE, 0 },
    { 800, 600, 60, 8, PIXEL_FORMAT_RGB888, COLOR_SPACE_SRGB, FALSE, FALSE, 0 },
    { 1024, 768, 60, 8, PIXEL_FORMAT_RGB888, COLOR_SPACE_SRGB, FALSE, FALSE, 0 },

    // HD modes
    { 1280, 720, 60, 8, PIXEL_FORMAT_RGB888, COLOR_SPACE_SRGB, FALSE, FALSE, 0 },
    { 1280, 1024, 60, 8, PIXEL_FORMAT_RGB888, COLOR_SPACE_SRGB, FALSE, FALSE, 0 },
    { 1366, 768, 60, 8, PIXEL_FORMAT_RGB888, COLOR_SPACE_SRGB, FALSE, FALSE, 0 },
    { 1440, 900, 60, 8, PIXEL_FORMAT_RGB888, COLOR_SPACE_SRGB, FALSE, FALSE, 0 },
    { 1600, 900, 60, 8, PIXEL_FORMAT_RGB888, COLOR_SPACE_SRGB, FALSE, FALSE, 0 },

    // Full HD
    { 1920, 1080, 60, 8, PIXEL_FORMAT_RGB888, COLOR_SPACE_SRGB, FALSE, FALSE, 0 },
    { 1920, 1080, 120, 8, PIXEL_FORMAT_RGB888, COLOR_SPACE_SRGB, FALSE, FALSE, 0 },
    { 1920, 1080, 144, 8, PIXEL_FORMAT_RGB888, COLOR_SPACE_SRGB, FALSE, FALSE, 0 },

    // WQHD/2K
    { 2560, 1440, 60, 8, PIXEL_FORMAT_RGB888, COLOR_SPACE_SRGB, FALSE, FALSE, 0 },
    { 2560, 1440, 120, 8, PIXEL_FORMAT_RGB888, COLOR_SPACE_SRGB, FALSE, FALSE, 0 },
    { 2560, 1440, 144, 8, PIXEL_FORMAT_RGB888, COLOR_SPACE_SRGB, FALSE, FALSE, 0 },
    { 2560, 1440, 165, 8, PIXEL_FORMAT_RGB888, COLOR_SPACE_SRGB, FALSE, FALSE, 0 },

    // 4K/UHD
    { 3840, 2160, 30, 8, PIXEL_FORMAT_RGB888, COLOR_SPACE_SRGB, FALSE, FALSE, 0 },
    { 3840, 2160, 60, 8, PIXEL_FORMAT_RGB888, COLOR_SPACE_SRGB, FALSE, FALSE, 0 },
    { 3840, 2160, 60, 10, PIXEL_FORMAT_RGB101010, COLOR_SPACE_REC_2020, FALSE, TRUE, 0 },
    { 3840, 2160, 120, 8, PIXEL_FORMAT_RGB888, COLOR_SPACE_SRGB, FALSE, FALSE, 0 },
    { 3840, 2160, 120, 10, PIXEL_FORMAT_RGB101010, COLOR_SPACE_REC_2020, FALSE, TRUE, 0 },
    { 3840, 2160, 144, 8, PIXEL_FORMAT_RGB888, COLOR_SPACE_SRGB, FALSE, FALSE, 0 },

    // 5K
    { 5120, 2880, 60, 8, PIXEL_FORMAT_RGB888, COLOR_SPACE_SRGB, FALSE, FALSE, 0 },
    { 5120, 2880, 60, 10, PIXEL_FORMAT_RGB101010, COLOR_SPACE_DCI_P3, FALSE, TRUE, 0 },

    // 8K/UHD-2
    { 7680, 4320, 30, 8, PIXEL_FORMAT_RGB888, COLOR_SPACE_SRGB, FALSE, FALSE, 0 },
    { 7680, 4320, 60, 8, PIXEL_FORMAT_RGB888, COLOR_SPACE_SRGB, FALSE, FALSE, 0 },
    { 7680, 4320, 60, 10, PIXEL_FORMAT_RGB101010, COLOR_SPACE_REC_2020, FALSE, TRUE, 0 },
};

static const UINT32 g_StandardModeCount = sizeof(g_StandardModes) / sizeof(DISPLAY_MODE);

// Forward declarations of interface methods
static IO_RETURN DisplayController_GetControllerInfo(IIODisplayController *pThis, DISPLAY_CONTROLLER_INFO *pInfo);
static IO_RETURN DisplayController_EnumerateModes(IIODisplayController *pThis, DISPLAY_MODE *pModes, UINT32 *puCount);
static IO_RETURN DisplayController_SetMode(IIODisplayController *pThis, CONST DISPLAY_MODE *pMode);
static IO_RETURN DisplayController_GetCurrentMode(IIODisplayController *pThis, DISPLAY_MODE *pMode);
static IO_RETURN DisplayController_AllocateFramebuffer(IIODisplayController *pThis, UINT32 uWidth, UINT32 uHeight, PIXEL_FORMAT Format, IIOFramebuffer **ppFramebuffer);
static IO_RETURN DisplayController_FreeFramebuffer(IIODisplayController *pThis, IIOFramebuffer *pFramebuffer);
static IO_RETURN DisplayController_EnableOutput(IIODisplayController *pThis, UINT32 uOutputIndex);
static IO_RETURN DisplayController_DisableOutput(IIODisplayController *pThis, UINT32 uOutputIndex);
static IO_RETURN DisplayController_GetEDID(IIODisplayController *pThis, UINT32 uOutputIndex, EDID_DATA *pEDID);
static IO_RETURN DisplayController_SetBrightness(IIODisplayController *pThis, UINT32 uOutputIndex, UINT32 uBrightness);
static IO_RETURN DisplayController_GetBrightness(IIODisplayController *pThis, UINT32 uOutputIndex, UINT32 *puBrightness);
static IO_RETURN DisplayController_EnableHDR(IIODisplayController *pThis, UINT32 uOutputIndex);
static IO_RETURN DisplayController_DisableHDR(IIODisplayController *pThis, UINT32 uOutputIndex);

static IO_RETURN Framebuffer_GetInfo(IIOFramebuffer *pThis, FRAMEBUFFER_INFO *pInfo);
static IO_RETURN Framebuffer_Map(IIOFramebuffer *pThis, VOID **ppAddress);
static IO_RETURN Framebuffer_Unmap(IIOFramebuffer *pThis);
static IO_RETURN Framebuffer_Blit(IIOFramebuffer *pThis, UINT32 uSrcX, UINT32 uSrcY, UINT32 uDstX, UINT32 uDstY, UINT32 uWidth, UINT32 uHeight);
static IO_RETURN Framebuffer_Fill(IIOFramebuffer *pThis, UINT32 uX, UINT32 uY, UINT32 uWidth, UINT32 uHeight, UINT32 uColor);
static IO_RETURN Framebuffer_SetPixel(IIOFramebuffer *pThis, UINT32 uX, UINT32 uY, UINT32 uColor);
static IO_RETURN Framebuffer_GetPixel(IIOFramebuffer *pThis, UINT32 uX, UINT32 uY, UINT32 *puColor);
static IO_RETURN Framebuffer_Pan(IIOFramebuffer *pThis, UINT32 uX, UINT32 uY);
static IO_RETURN Framebuffer_SetOffset(IIOFramebuffer *pThis, UINT64 uOffset);

/**
 * @brief Parse EDID manufacturer ID
 *
 * EDID manufacturer ID is encoded as 3 compressed ASCII characters (5 bits each).
 *
 * @param uManufacturerID   Manufacturer ID from EDID
 * @param pszName           Buffer to receive manufacturer name (4 bytes minimum)
 */
static VOID
EDIDParseManufacturerID(
    UINT16 uManufacturerID,
    CHAR8 *pszName
    )
{
    if (pszName == NULL) {
        return;
    }

    // Extract 3 5-bit characters (A-Z encoded as 1-26)
    pszName[0] = ((uManufacturerID >> 10) & 0x1F) + 'A' - 1;
    pszName[1] = ((uManufacturerID >> 5) & 0x1F) + 'A' - 1;
    pszName[2] = (uManufacturerID & 0x1F) + 'A' - 1;
    pszName[3] = '\0';
}

/**
 * @brief Validate EDID checksum
 *
 * @param pEDID         EDID data
 *
 * @retval TRUE         Checksum valid
 * @retval FALSE        Checksum invalid
 */
static BOOLEAN
EDIDValidateChecksum(
    CONST EDID_DATA *pEDID
    )
{
    UINT8 uChecksum = 0;
    CONST UINT8 *pData = (CONST UINT8 *)pEDID;
    UINT32 i;

    if (pEDID == NULL) {
        return FALSE;
    }

    // Sum all 128 bytes
    for (i = 0; i < 128; i++) {
        uChecksum += pData[i];
    }

    // Valid if sum is 0 (checksum is designed so total is 0)
    return (uChecksum == 0);
}

/**
 * @brief Parse EDID data
 *
 * @param pEDID         EDID data
 * @param pszBuffer     Buffer to receive parsed info (optional)
 * @param cbBufferSize  Buffer size
 *
 * @retval IO_SUCCESS       EDID parsed successfully
 * @retval IO_BAD_ARGUMENT  Invalid EDID data
 */
static IO_RETURN
EDIDParse(
    CONST EDID_DATA *pEDID,
    CHAR8 *pszBuffer,
    UINT32 cbBufferSize
    )
{
    CHAR8 szManufacturer[4];

    if (pEDID == NULL) {
        return IO_BAD_ARGUMENT;
    }

    // Validate header (00 FF FF FF FF FF FF 00)
    if (pEDID->Header[0] != 0x00 || pEDID->Header[1] != 0xFF ||
        pEDID->Header[2] != 0xFF || pEDID->Header[3] != 0xFF ||
        pEDID->Header[4] != 0xFF || pEDID->Header[5] != 0xFF ||
        pEDID->Header[6] != 0xFF || pEDID->Header[7] != 0x00) {
        printf("Display: Invalid EDID header\n");
        return IO_BAD_ARGUMENT;
    }

    // Validate checksum
    if (!EDIDValidateChecksum(pEDID)) {
        printf("Display: EDID checksum invalid\n");
        return IO_BAD_ARGUMENT;
    }

    // Parse manufacturer
    EDIDParseManufacturerID(pEDID->ManufacturerID, szManufacturer);

    printf("Display: EDID parsed successfully\n");
    printf("  Manufacturer: %s\n", szManufacturer);
    printf("  Product Code: 0x%04X\n", pEDID->ProductCode);
    printf("  Serial Number: 0x%08X\n", pEDID->SerialNumber);
    printf("  Week/Year: %u/%u\n", pEDID->WeekOfManufacture, 1990 + pEDID->YearOfManufacture);
    printf("  EDID Version: %u.%u\n", pEDID->EDIDVersion, pEDID->EDIDRevision);

    if (pszBuffer != NULL && cbBufferSize > 0) {
        snprintf(pszBuffer, cbBufferSize, "%s Product 0x%04X", szManufacturer, pEDID->ProductCode);
    }

    return IO_SUCCESS;
}

/**
 * @brief Lookup GPU device by vendor/device ID
 */
IO_RETURN
DisplayLookupDevice(
    UINT16 uVendorID,
    UINT16 uDeviceID,
    CONST GPU_DEVICE_ENTRY **ppEntry
    )
{
    UINT32 i;

    if (ppEntry == NULL) {
        return IO_BAD_ARGUMENT;
    }

    *ppEntry = NULL;

    for (i = 0; i < g_GPUDatabaseCount; i++) {
        if (g_GPUDatabase[i].VendorID == uVendorID &&
            g_GPUDatabase[i].DeviceID == uDeviceID) {
            *ppEntry = &g_GPUDatabase[i];
            return IO_SUCCESS;
        }
    }

    return IO_NO_MATCH;
}

/**
 * @brief Display Controller vtable
 */
static IIODisplayControllerVtbl g_DisplayControllerVtbl = {
    // IUnknown methods
    NULL,  // QueryInterface (TODO)
    NULL,  // AddRef (TODO)
    NULL,  // Release (TODO)

    // IIOService methods
    NULL,  // Probe (TODO)
    NULL,  // Start (TODO)
    NULL,  // Stop (TODO)
    NULL,  // Terminate (TODO)
    NULL,  // GetProperty (TODO)
    NULL,  // SetProperty (TODO)
    NULL,  // GetParentService (TODO)
    NULL,  // GetChildService (TODO)
    NULL,  // GetServiceState (TODO)
    NULL,  // GetServiceName (TODO)
    NULL,  // RegisterService (TODO)

    // IIODisplayController methods
    DisplayController_GetControllerInfo,
    DisplayController_EnumerateModes,
    DisplayController_SetMode,
    DisplayController_GetCurrentMode,
    DisplayController_AllocateFramebuffer,
    DisplayController_FreeFramebuffer,
    DisplayController_EnableOutput,
    DisplayController_DisableOutput,
    DisplayController_GetEDID,
    DisplayController_SetBrightness,
    DisplayController_GetBrightness,
    DisplayController_EnableHDR,
    DisplayController_DisableHDR,
};

/**
 * @brief Framebuffer vtable
 */
static IIOFramebufferVtbl g_FramebufferVtbl = {
    // IUnknown methods
    NULL,  // QueryInterface (TODO)
    NULL,  // AddRef (TODO)
    NULL,  // Release (TODO)

    // IIOService methods
    NULL,  // Probe (TODO)
    NULL,  // Start (TODO)
    NULL,  // Stop (TODO)
    NULL,  // Terminate (TODO)
    NULL,  // GetProperty (TODO)
    NULL,  // SetProperty (TODO)
    NULL,  // GetParentService (TODO)
    NULL,  // GetChildService (TODO)
    NULL,  // GetServiceState (TODO)
    NULL,  // GetServiceName (TODO)
    NULL,  // RegisterService (TODO)

    // IIOFramebuffer methods
    Framebuffer_GetInfo,
    Framebuffer_Map,
    Framebuffer_Unmap,
    Framebuffer_Blit,
    Framebuffer_Fill,
    Framebuffer_SetPixel,
    Framebuffer_GetPixel,
    Framebuffer_Pan,
    Framebuffer_SetOffset,
};

// Implementation of DisplayController methods

static IO_RETURN
DisplayController_GetControllerInfo(
    IIODisplayController *pThis,
    DISPLAY_CONTROLLER_INFO *pInfo
    )
{
    DISPLAY_CONTROLLER_IMPL *pImpl = (DISPLAY_CONTROLLER_IMPL *)pThis;

    if (pImpl == NULL || pInfo == NULL) {
        return IO_BAD_ARGUMENT;
    }

    memcpy(pInfo, &pImpl->Info, sizeof(DISPLAY_CONTROLLER_INFO));
    return IO_SUCCESS;
}

static IO_RETURN
DisplayController_EnumerateModes(
    IIODisplayController *pThis,
    DISPLAY_MODE *pModes,
    UINT32 *puCount
    )
{
    UINT32 i;

    if (pThis == NULL || puCount == NULL) {
        return IO_BAD_ARGUMENT;
    }

    if (pModes == NULL) {
        // Just return count
        *puCount = g_StandardModeCount;
        return IO_SUCCESS;
    }

    if (*puCount < g_StandardModeCount) {
        *puCount = g_StandardModeCount;
        return IO_NO_SPACE;
    }

    // Copy standard modes
    for (i = 0; i < g_StandardModeCount; i++) {
        memcpy(&pModes[i], &g_StandardModes[i], sizeof(DISPLAY_MODE));
    }

    *puCount = g_StandardModeCount;
    return IO_SUCCESS;
}

static IO_RETURN
DisplayController_SetMode(
    IIODisplayController *pThis,
    CONST DISPLAY_MODE *pMode
    )
{
    DISPLAY_CONTROLLER_IMPL *pImpl = (DISPLAY_CONTROLLER_IMPL *)pThis;

    if (pImpl == NULL || pMode == NULL) {
        return IO_BAD_ARGUMENT;
    }

    printf("Display: Setting mode %ux%u@%uHz %ubpc\n",
           pMode->Width, pMode->Height, pMode->RefreshRate, pMode->BitDepth);

    // TODO: Implement actual mode setting (VBE, VESA, etc.)

    memcpy(&pImpl->CurrentMode, pMode, sizeof(DISPLAY_MODE));
    return IO_SUCCESS;
}

static IO_RETURN
DisplayController_GetCurrentMode(
    IIODisplayController *pThis,
    DISPLAY_MODE *pMode
    )
{
    DISPLAY_CONTROLLER_IMPL *pImpl = (DISPLAY_CONTROLLER_IMPL *)pThis;

    if (pImpl == NULL || pMode == NULL) {
        return IO_BAD_ARGUMENT;
    }

    memcpy(pMode, &pImpl->CurrentMode, sizeof(DISPLAY_MODE));
    return IO_SUCCESS;
}

static IO_RETURN
DisplayController_AllocateFramebuffer(
    IIODisplayController *pThis,
    UINT32 uWidth,
    UINT32 uHeight,
    PIXEL_FORMAT Format,
    IIOFramebuffer **ppFramebuffer
    )
{
    FRAMEBUFFER_IMPL *pFB;
    UINT32 uBytesPerPixel;

    if (pThis == NULL || ppFramebuffer == NULL) {
        return IO_BAD_ARGUMENT;
    }

    // Allocate framebuffer structure
    pFB = (FRAMEBUFFER_IMPL *)malloc(sizeof(FRAMEBUFFER_IMPL));
    if (pFB == NULL) {
        return IO_NO_MEMORY;
    }

    memset(pFB, 0, sizeof(FRAMEBUFFER_IMPL));

    // Initialize vtable
    pFB->Vtbl.lpVtbl = &g_FramebufferVtbl;
    pFB->uRefCount = 1;

    // Setup framebuffer info
    pFB->Info.Width = uWidth;
    pFB->Info.Height = uHeight;
    pFB->Info.PixelFormat = Format;

    // Calculate bytes per pixel
    switch (Format) {
        case PIXEL_FORMAT_RGB888:
        case PIXEL_FORMAT_BGR888:
            uBytesPerPixel = 3;
            pFB->Info.BitsPerPixel = 24;
            break;
        case PIXEL_FORMAT_RGBX8888:
        case PIXEL_FORMAT_RGBA8888:
        case PIXEL_FORMAT_BGRX8888:
        case PIXEL_FORMAT_BGRA8888:
            uBytesPerPixel = 4;
            pFB->Info.BitsPerPixel = 32;
            break;
        case PIXEL_FORMAT_RGB565:
            uBytesPerPixel = 2;
            pFB->Info.BitsPerPixel = 16;
            break;
        default:
            uBytesPerPixel = 4;
            pFB->Info.BitsPerPixel = 32;
            break;
    }

    pFB->Info.Pitch = uWidth * uBytesPerPixel;
    pFB->Info.Size = pFB->Info.Pitch * uHeight;

    // TODO: Allocate actual video memory
    pFB->Info.PhysicalAddress = 0xB8000;  // Placeholder

    *ppFramebuffer = (IIOFramebuffer *)pFB;

    printf("Display: Allocated framebuffer %ux%u (%u bytes)\n",
           uWidth, uHeight, (UINT32)pFB->Info.Size);

    return IO_SUCCESS;
}

static IO_RETURN
DisplayController_FreeFramebuffer(
    IIODisplayController *pThis,
    IIOFramebuffer *pFramebuffer
    )
{
    FRAMEBUFFER_IMPL *pFB = (FRAMEBUFFER_IMPL *)pFramebuffer;

    if (pThis == NULL || pFB == NULL) {
        return IO_BAD_ARGUMENT;
    }

    // Unmap if mapped
    if (pFB->bMapped) {
        Framebuffer_Unmap(pFramebuffer);
    }

    free(pFB);

    printf("Display: Freed framebuffer\n");
    return IO_SUCCESS;
}

static IO_RETURN
DisplayController_EnableOutput(
    IIODisplayController *pThis,
    UINT32 uOutputIndex
    )
{
    if (pThis == NULL) {
        return IO_BAD_ARGUMENT;
    }

    printf("Display: Enabled output %u\n", uOutputIndex);
    return IO_SUCCESS;
}

static IO_RETURN
DisplayController_DisableOutput(
    IIODisplayController *pThis,
    UINT32 uOutputIndex
    )
{
    if (pThis == NULL) {
        return IO_BAD_ARGUMENT;
    }

    printf("Display: Disabled output %u\n", uOutputIndex);
    return IO_SUCCESS;
}

static IO_RETURN
DisplayController_GetEDID(
    IIODisplayController *pThis,
    UINT32 uOutputIndex,
    EDID_DATA *pEDID
    )
{
    if (pThis == NULL || pEDID == NULL) {
        return IO_BAD_ARGUMENT;
    }

    // TODO: Read actual EDID from display
    printf("Display: Reading EDID from output %u\n", uOutputIndex);

    // For now, return error (no display connected in simulation)
    return IO_NO_DEVICE;
}

static IO_RETURN
DisplayController_SetBrightness(
    IIODisplayController *pThis,
    UINT32 uOutputIndex,
    UINT32 uBrightness
    )
{
    if (pThis == NULL || uBrightness > 100) {
        return IO_BAD_ARGUMENT;
    }

    printf("Display: Set brightness on output %u to %u%%\n", uOutputIndex, uBrightness);
    return IO_SUCCESS;
}

static IO_RETURN
DisplayController_GetBrightness(
    IIODisplayController *pThis,
    UINT32 uOutputIndex,
    UINT32 *puBrightness
    )
{
    if (pThis == NULL || puBrightness == NULL) {
        return IO_BAD_ARGUMENT;
    }

    // Return default brightness
    *puBrightness = 100;
    return IO_SUCCESS;
}

static IO_RETURN
DisplayController_EnableHDR(
    IIODisplayController *pThis,
    UINT32 uOutputIndex
    )
{
    DISPLAY_CONTROLLER_IMPL *pImpl = (DISPLAY_CONTROLLER_IMPL *)pThis;

    if (pImpl == NULL) {
        return IO_BAD_ARGUMENT;
    }

    if (!(pImpl->Info.Capabilities & GPU_CAP_HDR10)) {
        printf("Display: HDR not supported by GPU\n");
        return IO_UNSUPPORTED;
    }

    printf("Display: Enabled HDR on output %u\n", uOutputIndex);
    return IO_SUCCESS;
}

static IO_RETURN
DisplayController_DisableHDR(
    IIODisplayController *pThis,
    UINT32 uOutputIndex
    )
{
    if (pThis == NULL) {
        return IO_BAD_ARGUMENT;
    }

    printf("Display: Disabled HDR on output %u\n", uOutputIndex);
    return IO_SUCCESS;
}

// Implementation of Framebuffer methods

static IO_RETURN
Framebuffer_GetInfo(
    IIOFramebuffer *pThis,
    FRAMEBUFFER_INFO *pInfo
    )
{
    FRAMEBUFFER_IMPL *pImpl = (FRAMEBUFFER_IMPL *)pThis;

    if (pImpl == NULL || pInfo == NULL) {
        return IO_BAD_ARGUMENT;
    }

    memcpy(pInfo, &pImpl->Info, sizeof(FRAMEBUFFER_INFO));
    return IO_SUCCESS;
}

static IO_RETURN
Framebuffer_Map(
    IIOFramebuffer *pThis,
    VOID **ppAddress
    )
{
    FRAMEBUFFER_IMPL *pImpl = (FRAMEBUFFER_IMPL *)pThis;

    if (pImpl == NULL || ppAddress == NULL) {
        return IO_BAD_ARGUMENT;
    }

    if (pImpl->bMapped) {
        *ppAddress = pImpl->pMappedAddress;
        return IO_SUCCESS;
    }

    // TODO: Map physical framebuffer address to virtual memory
    pImpl->pMappedAddress = (VOID *)(UINTN)pImpl->Info.PhysicalAddress;
    pImpl->bMapped = TRUE;

    *ppAddress = pImpl->pMappedAddress;

    printf("Display: Mapped framebuffer at 0x%llX\n", (UINT64)(UINTN)pImpl->pMappedAddress);
    return IO_SUCCESS;
}

static IO_RETURN
Framebuffer_Unmap(
    IIOFramebuffer *pThis
    )
{
    FRAMEBUFFER_IMPL *pImpl = (FRAMEBUFFER_IMPL *)pThis;

    if (pImpl == NULL) {
        return IO_BAD_ARGUMENT;
    }

    if (!pImpl->bMapped) {
        return IO_SUCCESS;
    }

    // TODO: Unmap virtual memory
    pImpl->pMappedAddress = NULL;
    pImpl->bMapped = FALSE;

    printf("Display: Unmapped framebuffer\n");
    return IO_SUCCESS;
}

static IO_RETURN
Framebuffer_Blit(
    IIOFramebuffer *pThis,
    UINT32 uSrcX,
    UINT32 uSrcY,
    UINT32 uDstX,
    UINT32 uDstY,
    UINT32 uWidth,
    UINT32 uHeight
    )
{
    if (pThis == NULL) {
        return IO_BAD_ARGUMENT;
    }

    // TODO: Implement hardware-accelerated blit
    printf("Display: Blit (%u,%u)->(%u,%u) %ux%u\n", uSrcX, uSrcY, uDstX, uDstY, uWidth, uHeight);
    return IO_SUCCESS;
}

static IO_RETURN
Framebuffer_Fill(
    IIOFramebuffer *pThis,
    UINT32 uX,
    UINT32 uY,
    UINT32 uWidth,
    UINT32 uHeight,
    UINT32 uColor
    )
{
    if (pThis == NULL) {
        return IO_BAD_ARGUMENT;
    }

    // TODO: Implement hardware-accelerated fill
    printf("Display: Fill (%u,%u) %ux%u color=0x%08X\n", uX, uY, uWidth, uHeight, uColor);
    return IO_SUCCESS;
}

static IO_RETURN
Framebuffer_SetPixel(
    IIOFramebuffer *pThis,
    UINT32 uX,
    UINT32 uY,
    UINT32 uColor
    )
{
    FRAMEBUFFER_IMPL *pImpl = (FRAMEBUFFER_IMPL *)pThis;
    UINT32 uOffset;
    volatile UINT32 *pPixel;

    if (pImpl == NULL || !pImpl->bMapped) {
        return IO_BAD_ARGUMENT;
    }

    if (uX >= pImpl->Info.Width || uY >= pImpl->Info.Height) {
        return IO_BAD_ARGUMENT;
    }

    uOffset = uY * pImpl->Info.Pitch + (uX * (pImpl->Info.BitsPerPixel / 8));
    pPixel = (volatile UINT32 *)((UINT8 *)pImpl->pMappedAddress + uOffset);
    *pPixel = uColor;

    return IO_SUCCESS;
}

static IO_RETURN
Framebuffer_GetPixel(
    IIOFramebuffer *pThis,
    UINT32 uX,
    UINT32 uY,
    UINT32 *puColor
    )
{
    FRAMEBUFFER_IMPL *pImpl = (FRAMEBUFFER_IMPL *)pThis;
    UINT32 uOffset;
    volatile UINT32 *pPixel;

    if (pImpl == NULL || puColor == NULL || !pImpl->bMapped) {
        return IO_BAD_ARGUMENT;
    }

    if (uX >= pImpl->Info.Width || uY >= pImpl->Info.Height) {
        return IO_BAD_ARGUMENT;
    }

    uOffset = uY * pImpl->Info.Pitch + (uX * (pImpl->Info.BitsPerPixel / 8));
    pPixel = (volatile UINT32 *)((UINT8 *)pImpl->pMappedAddress + uOffset);
    *puColor = *pPixel;

    return IO_SUCCESS;
}

static IO_RETURN
Framebuffer_Pan(
    IIOFramebuffer *pThis,
    UINT32 uX,
    UINT32 uY
    )
{
    if (pThis == NULL) {
        return IO_BAD_ARGUMENT;
    }

    // TODO: Implement display panning
    printf("Display: Pan to (%u,%u)\n", uX, uY);
    return IO_SUCCESS;
}

static IO_RETURN
Framebuffer_SetOffset(
    IIOFramebuffer *pThis,
    UINT64 uOffset
    )
{
    if (pThis == NULL) {
        return IO_BAD_ARGUMENT;
    }

    // TODO: Implement framebuffer offset
    printf("Display: Set offset to 0x%llX\n", uOffset);
    return IO_SUCCESS;
}

/**
 * @brief Create a display controller instance
 */
IO_RETURN
IODisplayControllerCreate(
    CONST CHAR8 *pszName,
    IIODisplayController **ppController
    )
{
    DISPLAY_CONTROLLER_IMPL *pImpl;

    if (ppController == NULL) {
        return IO_BAD_ARGUMENT;
    }

    pImpl = (DISPLAY_CONTROLLER_IMPL *)malloc(sizeof(DISPLAY_CONTROLLER_IMPL));
    if (pImpl == NULL) {
        return IO_NO_MEMORY;
    }

    memset(pImpl, 0, sizeof(DISPLAY_CONTROLLER_IMPL));

    // Initialize vtable
    pImpl->Vtbl.lpVtbl = &g_DisplayControllerVtbl;
    pImpl->uRefCount = 1;
    pImpl->bInitialized = TRUE;

    // Setup default info
    if (pszName != NULL) {
        strncpy(pImpl->Info.DeviceName, pszName, sizeof(pImpl->Info.DeviceName) - 1);
    } else {
        strncpy(pImpl->Info.DeviceName, "Generic Display Controller", sizeof(pImpl->Info.DeviceName) - 1);
    }

    pImpl->Info.Type = GPU_TYPE_DISCRETE;
    pImpl->Info.VRAMSize = 256 * 1024 * 1024;  // 256MB default
    pImpl->Info.VRAMType = VRAM_TYPE_GDDR6;
    pImpl->Info.Capabilities = GPU_CAP_2D_ACCEL | GPU_CAP_3D_ACCEL | GPU_CAP_MULTI_MONITOR;
    pImpl->Info.NumOutputs = 1;
    pImpl->Info.MaxResolutionX = 3840;
    pImpl->Info.MaxResolutionY = 2160;

    // Setup default mode (1920x1080@60Hz)
    pImpl->CurrentMode.Width = 1920;
    pImpl->CurrentMode.Height = 1080;
    pImpl->CurrentMode.RefreshRate = 60;
    pImpl->CurrentMode.BitDepth = 8;
    pImpl->CurrentMode.PixelFormat = PIXEL_FORMAT_RGB888;
    pImpl->CurrentMode.ColorSpace = COLOR_SPACE_SRGB;

    *ppController = (IIODisplayController *)pImpl;

    printf("Display: Created controller '%s'\n", pImpl->Info.DeviceName);
    return IO_SUCCESS;
}

/**
 * @brief Initialize display subsystem
 */
IO_RETURN
DisplayInitialize(
    VOID
    )
{
    if (g_DisplaySubsystem.bInitialized) {
        return IO_SUCCESS;
    }

    printf("Display: Initializing display subsystem\n");
    printf("Display: GPU database contains %u entries\n", g_GPUDatabaseCount);
    printf("Display: Standard mode database contains %u modes\n", g_StandardModeCount);

    g_DisplaySubsystem.bInitialized = TRUE;
    g_DisplaySubsystem.uControllerCount = 0;

    return IO_SUCCESS;
}

/**
 * @brief Shutdown display subsystem
 */
IO_RETURN
DisplayShutdown(
    VOID
    )
{
    if (!g_DisplaySubsystem.bInitialized) {
        return IO_SUCCESS;
    }

    printf("Display: Shutting down display subsystem\n");

    g_DisplaySubsystem.bInitialized = FALSE;
    g_DisplaySubsystem.uControllerCount = 0;

    return IO_SUCCESS;
}
