# NuxCompilerSetup.cmake
# Comprehensive compiler detection and configuration for NUX

function(nux_detect_compiler)
    set(NUX_COMPILER_VENDOR "unknown" PARENT_SCOPE)

    # Detect compiler vendor
    if(CMAKE_C_COMPILER_ID MATCHES "GNU")
        set(NUX_COMPILER_VENDOR "gcc" PARENT_SCOPE)
        message(STATUS "Detected GCC compiler")

    elseif(CMAKE_C_COMPILER_ID MATCHES "Clang")
        if(CMAKE_C_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC")
            set(NUX_COMPILER_VENDOR "clang-cl" PARENT_SCOPE)
            message(STATUS "Detected Clang-CL (MSVC frontend)")
        else()
            set(NUX_COMPILER_VENDOR "clang" PARENT_SCOPE)
            message(STATUS "Detected Clang/LLVM compiler")
        endif()

    elseif(CMAKE_C_COMPILER_ID MATCHES "Intel")
        set(NUX_COMPILER_VENDOR "intel" PARENT_SCOPE)
        message(STATUS "Detected Intel C Compiler")

    elseif(CMAKE_C_COMPILER_ID MATCHES "IntelLLVM")
        set(NUX_COMPILER_VENDOR "intel-llvm" PARENT_SCOPE)
        message(STATUS "Detected Intel LLVM-based Compiler (ICX)")

    elseif(CMAKE_C_COMPILER_ID MATCHES "MSVC")
        set(NUX_COMPILER_VENDOR "msvc" PARENT_SCOPE)
        message(STATUS "Detected Microsoft Visual C++")

    elseif(CMAKE_C_COMPILER_ID MATCHES "SunPro")
        set(NUX_COMPILER_VENDOR "sunstudio" PARENT_SCOPE)
        message(STATUS "Detected Sun Studio compiler")

    elseif(CMAKE_C_COMPILER_ID MATCHES "HP")
        set(NUX_COMPILER_VENDOR "hpux" PARENT_SCOPE)
        message(STATUS "Detected HP-UX compiler")

    elseif(CMAKE_C_COMPILER_ID MATCHES "XL")
        set(NUX_COMPILER_VENDOR "xlc" PARENT_SCOPE)
        message(STATUS "Detected IBM XL C/C++ compiler")

    elseif(CMAKE_C_COMPILER_ID MATCHES "TinyCC")
        set(NUX_COMPILER_VENDOR "tcc" PARENT_SCOPE)
        message(STATUS "Detected Tiny C Compiler")

    elseif(CMAKE_C_COMPILER_ID MATCHES "Watcom")
        set(NUX_COMPILER_VENDOR "watcom" PARENT_SCOPE)
        message(STATUS "Detected Open Watcom compiler")

    elseif(CMAKE_C_COMPILER_ID MATCHES "PCC")
        set(NUX_COMPILER_VENDOR "pcc" PARENT_SCOPE)
        message(STATUS "Detected Portable C Compiler")

    elseif(CMAKE_C_COMPILER_ID MATCHES "LCC")
        set(NUX_COMPILER_VENDOR "lcc" PARENT_SCOPE)
        message(STATUS "Detected LCC compiler")

    elseif(CMAKE_C_COMPILER_ID MATCHES "Open64")
        set(NUX_COMPILER_VENDOR "open64" PARENT_SCOPE)
        message(STATUS "Detected Open64 compiler")

    else()
        # Try to detect by compiler executable name or define test
        if(CMAKE_C_COMPILER MATCHES "pcc")
            set(NUX_COMPILER_VENDOR "pcc" PARENT_SCOPE)
            message(STATUS "Detected PCC by executable name")
        elseif(CMAKE_C_COMPILER MATCHES "tcc")
            set(NUX_COMPILER_VENDOR "tcc" PARENT_SCOPE)
            message(STATUS "Detected TCC by executable name")
        elseif(CMAKE_C_COMPILER MATCHES "lcc")
            set(NUX_COMPILER_VENDOR "lcc" PARENT_SCOPE)
            message(STATUS "Detected LCC by executable name")
        elseif(CMAKE_C_COMPILER MATCHES "wcl")
            set(NUX_COMPILER_VENDOR "watcom" PARENT_SCOPE)
            message(STATUS "Detected Watcom by executable name")
        else()
            message(WARNING "Unknown compiler: ${CMAKE_C_COMPILER_ID}, using generic settings")
            set(NUX_COMPILER_VENDOR "generic" PARENT_SCOPE)
        endif()
    endif()
endfunction()

function(nux_setup_compiler_flags)
    # Get compiler vendor from parent scope
    set(VENDOR ${NUX_COMPILER_VENDOR})

    # Initialize flag variables
    set(NUX_CFLAGS_OPT "" PARENT_SCOPE)
    set(NUX_CFLAGS_DEBUG "" PARENT_SCOPE)
    set(NUX_CFLAGS_WARN "" PARENT_SCOPE)
    set(NUX_CFLAGS_NOSTDINC "" PARENT_SCOPE)
    set(NUX_CFLAGS_FREESTANDING "" PARENT_SCOPE)
    set(NUX_CFLAGS_PIC "" PARENT_SCOPE)
    set(NUX_CFLAGS_SECTION "" PARENT_SCOPE)
    set(NUX_LDFLAGS_NOSTDLIB "" PARENT_SCOPE)
    set(NUX_LDFLAGS_STATIC "" PARENT_SCOPE)

    # Set flags based on compiler vendor
    if(VENDOR MATCHES "gcc|clang|intel-llvm|open64")
        set(NUX_CFLAGS_OPT "-O2" PARENT_SCOPE)
        set(NUX_CFLAGS_DEBUG "-g" PARENT_SCOPE)
        set(NUX_CFLAGS_WARN "-Wall -Wextra" PARENT_SCOPE)
        set(NUX_CFLAGS_NOSTDINC "-nostdinc" PARENT_SCOPE)
        set(NUX_CFLAGS_FREESTANDING "-ffreestanding" PARENT_SCOPE)
        set(NUX_CFLAGS_PIC "-fPIC" PARENT_SCOPE)
        set(NUX_CFLAGS_SECTION "-fdata-sections -ffunction-sections" PARENT_SCOPE)
        set(NUX_LDFLAGS_NOSTDLIB "-nostdlib" PARENT_SCOPE)
        set(NUX_LDFLAGS_STATIC "-static" PARENT_SCOPE)

    elseif(VENDOR STREQUAL "intel")
        set(NUX_CFLAGS_OPT "-O2" PARENT_SCOPE)
        set(NUX_CFLAGS_DEBUG "-g" PARENT_SCOPE)
        set(NUX_CFLAGS_WARN "-Wall -w2" PARENT_SCOPE)
        set(NUX_CFLAGS_NOSTDINC "-nostdinc" PARENT_SCOPE)
        set(NUX_CFLAGS_FREESTANDING "-freestanding" PARENT_SCOPE)
        set(NUX_CFLAGS_PIC "-fPIC" PARENT_SCOPE)
        set(NUX_CFLAGS_SECTION "-ffunction-sections -fdata-sections" PARENT_SCOPE)
        set(NUX_LDFLAGS_NOSTDLIB "-nostdlib" PARENT_SCOPE)
        set(NUX_LDFLAGS_STATIC "-static" PARENT_SCOPE)

    elseif(VENDOR MATCHES "msvc|clang-cl")
        set(NUX_CFLAGS_OPT "/O2" PARENT_SCOPE)
        set(NUX_CFLAGS_DEBUG "/Zi" PARENT_SCOPE)
        set(NUX_CFLAGS_WARN "/W3" PARENT_SCOPE)
        set(NUX_CFLAGS_NOSTDINC "/X" PARENT_SCOPE)
        set(NUX_CFLAGS_FREESTANDING "/kernel" PARENT_SCOPE)
        set(NUX_CFLAGS_PIC "" PARENT_SCOPE)
        set(NUX_CFLAGS_SECTION "/Gy" PARENT_SCOPE)
        set(NUX_LDFLAGS_NOSTDLIB "/NODEFAULTLIB" PARENT_SCOPE)
        set(NUX_LDFLAGS_STATIC "/MT" PARENT_SCOPE)

    elseif(VENDOR STREQUAL "sunstudio")
        set(NUX_CFLAGS_OPT "-xO2" PARENT_SCOPE)
        set(NUX_CFLAGS_DEBUG "-g" PARENT_SCOPE)
        set(NUX_CFLAGS_WARN "-v" PARENT_SCOPE)
        set(NUX_CFLAGS_NOSTDINC "-Xc" PARENT_SCOPE)
        set(NUX_CFLAGS_FREESTANDING "" PARENT_SCOPE)
        set(NUX_CFLAGS_PIC "-KPIC" PARENT_SCOPE)
        set(NUX_CFLAGS_SECTION "" PARENT_SCOPE)
        set(NUX_LDFLAGS_NOSTDLIB "-nolib" PARENT_SCOPE)
        set(NUX_LDFLAGS_STATIC "-Bstatic" PARENT_SCOPE)

    elseif(VENDOR STREQUAL "hpux")
        set(NUX_CFLAGS_OPT "+O2" PARENT_SCOPE)
        set(NUX_CFLAGS_DEBUG "-g" PARENT_SCOPE)
        set(NUX_CFLAGS_WARN "+w" PARENT_SCOPE)
        set(NUX_CFLAGS_NOSTDINC "" PARENT_SCOPE)
        set(NUX_CFLAGS_FREESTANDING "" PARENT_SCOPE)
        set(NUX_CFLAGS_PIC "+Z" PARENT_SCOPE)
        set(NUX_CFLAGS_SECTION "" PARENT_SCOPE)
        set(NUX_LDFLAGS_NOSTDLIB "-nodefaultlibs" PARENT_SCOPE)
        set(NUX_LDFLAGS_STATIC "-Wl,-a,archive" PARENT_SCOPE)

    elseif(VENDOR STREQUAL "xlc")
        set(NUX_CFLAGS_OPT "-O2" PARENT_SCOPE)
        set(NUX_CFLAGS_DEBUG "-g" PARENT_SCOPE)
        set(NUX_CFLAGS_WARN "-qinfo=all" PARENT_SCOPE)
        set(NUX_CFLAGS_NOSTDINC "-qnoinclude" PARENT_SCOPE)
        set(NUX_CFLAGS_FREESTANDING "" PARENT_SCOPE)
        set(NUX_CFLAGS_PIC "-qpic" PARENT_SCOPE)
        set(NUX_CFLAGS_SECTION "" PARENT_SCOPE)
        set(NUX_LDFLAGS_NOSTDLIB "-nostdlib" PARENT_SCOPE)
        set(NUX_LDFLAGS_STATIC "-bstatic" PARENT_SCOPE)

    elseif(VENDOR STREQUAL "watcom")
        set(NUX_CFLAGS_OPT "-ox" PARENT_SCOPE)
        set(NUX_CFLAGS_DEBUG "-d2" PARENT_SCOPE)
        set(NUX_CFLAGS_WARN "-wx" PARENT_SCOPE)
        set(NUX_CFLAGS_NOSTDINC "-zl" PARENT_SCOPE)
        set(NUX_CFLAGS_FREESTANDING "" PARENT_SCOPE)
        set(NUX_CFLAGS_PIC "" PARENT_SCOPE)
        set(NUX_CFLAGS_SECTION "" PARENT_SCOPE)
        set(NUX_LDFLAGS_NOSTDLIB "" PARENT_SCOPE)
        set(NUX_LDFLAGS_STATIC "" PARENT_SCOPE)

    elseif(VENDOR MATCHES "tcc|pcc|lcc")
        set(NUX_CFLAGS_OPT "-O" PARENT_SCOPE)
        set(NUX_CFLAGS_DEBUG "-g" PARENT_SCOPE)
        set(NUX_CFLAGS_WARN "-Wall" PARENT_SCOPE)
        set(NUX_CFLAGS_NOSTDINC "-nostdinc" PARENT_SCOPE)
        set(NUX_CFLAGS_FREESTANDING "" PARENT_SCOPE)
        set(NUX_CFLAGS_PIC "" PARENT_SCOPE)
        set(NUX_CFLAGS_SECTION "" PARENT_SCOPE)
        set(NUX_LDFLAGS_NOSTDLIB "-nostdlib" PARENT_SCOPE)
        set(NUX_LDFLAGS_STATIC "-static" PARENT_SCOPE)

    else()
        # Generic fallback
        set(NUX_CFLAGS_OPT "-O" PARENT_SCOPE)
        set(NUX_CFLAGS_DEBUG "-g" PARENT_SCOPE)
        set(NUX_CFLAGS_WARN "" PARENT_SCOPE)
        set(NUX_CFLAGS_NOSTDINC "" PARENT_SCOPE)
        set(NUX_CFLAGS_FREESTANDING "" PARENT_SCOPE)
        set(NUX_CFLAGS_PIC "" PARENT_SCOPE)
        set(NUX_CFLAGS_SECTION "" PARENT_SCOPE)
        set(NUX_LDFLAGS_NOSTDLIB "" PARENT_SCOPE)
        set(NUX_LDFLAGS_STATIC "" PARENT_SCOPE)
    endif()

    # Apply flags to CMake variables
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${NUX_CFLAGS_NOSTDINC} ${NUX_CFLAGS_FREESTANDING}" PARENT_SCOPE)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${NUX_CFLAGS_NOSTDINC} ${NUX_CFLAGS_FREESTANDING}" PARENT_SCOPE)

    if(CMAKE_BUILD_TYPE STREQUAL "Debug")
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${NUX_CFLAGS_DEBUG}" PARENT_SCOPE)
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${NUX_CFLAGS_DEBUG}" PARENT_SCOPE)
    else()
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${NUX_CFLAGS_OPT}" PARENT_SCOPE)
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${NUX_CFLAGS_OPT}" PARENT_SCOPE)
    endif()

endfunction()
