/*
 * Configuration Generator Implementation
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ananke/anxconfig.h>

/* Generator structure */
typedef struct {
    IConfigGenerator Interface;
    UINTN RefCount;
} ConfigGenerator;

/* IUnknown methods */
static HRESULT ANXAPI Generator_QueryInterface(
    IConfigGenerator *This,
    REFIID riid,
    VOID **ppvObject
)
{
    if (ppvObject == NULL) {
        return E_POINTER;
    }

    if (IsEqualGUID(riid, &IID_IUnknown) ||
        IsEqualGUID(riid, &IID_IConfigGenerator)) {
        *ppvObject = This;
        This->Vtbl->AddRef(This);
        return S_OK;
    }

    *ppvObject = NULL;
    return E_NOINTERFACE;
}

static UINTN ANXAPI Generator_AddRef(IConfigGenerator *This)
{
    ConfigGenerator *gen = (ConfigGenerator *)This;
    return ++gen->RefCount;
}

static UINTN ANXAPI Generator_Release(IConfigGenerator *This)
{
    ConfigGenerator *gen = (ConfigGenerator *)This;
    UINTN refCount = --gen->RefCount;

    if (refCount == 0) {
        free(gen);
    }

    return refCount;
}

/* Generator methods */
static HRESULT ANXAPI Generator_GenerateCMakeCache(
    IConfigGenerator *This,
    IConfigDatabase *Database,
    CONST CHAR8 *OutputPath
)
{
    FILE *f;

    if (Database == NULL || OutputPath == NULL) {
        return E_POINTER;
    }

    printf("[Generator] Generating CMake cache: %s\n", OutputPath);

    f = fopen(OutputPath, "w");
    if (!f) {
        return E_FAIL;
    }

    fprintf(f, "# ANXCONFIG Generated CMake Cache\n");
    fprintf(f, "# This file is automatically generated. DO NOT EDIT.\n");
    fprintf(f, "\n");
    fprintf(f, "# Example configuration\n");
    fprintf(f, "set(CONFIG_EXAMPLE ON CACHE BOOL \"Example configuration option\")\n");
    fprintf(f, "\n");

    fclose(f);
    return S_OK;
}

static HRESULT ANXAPI Generator_GenerateCHeader(
    IConfigGenerator *This,
    IConfigDatabase *Database,
    CONST CHAR8 *OutputPath
)
{
    FILE *f;

    if (Database == NULL || OutputPath == NULL) {
        return E_POINTER;
    }

    printf("[Generator] Generating C header: %s\n", OutputPath);

    f = fopen(OutputPath, "w");
    if (!f) {
        return E_FAIL;
    }

    fprintf(f, "/* ANXCONFIG Generated Configuration Header */\n");
    fprintf(f, "/* This file is automatically generated. DO NOT EDIT. */\n");
    fprintf(f, "\n");
    fprintf(f, "#ifndef __CONFIG_H__\n");
    fprintf(f, "#define __CONFIG_H__\n");
    fprintf(f, "\n");
    fprintf(f, "#define CONFIG_EXAMPLE 1\n");
    fprintf(f, "\n");
    fprintf(f, "#endif /* __CONFIG_H__ */\n");

    fclose(f);
    return S_OK;
}

static HRESULT ANXAPI Generator_GenerateMakefile(
    IConfigGenerator *This,
    IConfigDatabase *Database,
    CONST CHAR8 *OutputPath
)
{
    FILE *f;

    if (Database == NULL || OutputPath == NULL) {
        return E_POINTER;
    }

    printf("[Generator] Generating Makefile: %s\n", OutputPath);

    f = fopen(OutputPath, "w");
    if (!f) {
        return E_FAIL;
    }

    fprintf(f, "# ANXCONFIG Generated Makefile Fragment\n");
    fprintf(f, "# This file is automatically generated. DO NOT EDIT.\n");
    fprintf(f, "\n");
    fprintf(f, "CONFIG_EXAMPLE := y\n");
    fprintf(f, "\n");

    fclose(f);
    return S_OK;
}

static HRESULT ANXAPI Generator_GenerateAutoconf(
    IConfigGenerator *This,
    IConfigDatabase *Database,
    CONST CHAR8 *OutputPath
)
{
    FILE *f;

    if (Database == NULL || OutputPath == NULL) {
        return E_POINTER;
    }

    printf("[Generator] Generating autoconf: %s\n", OutputPath);

    f = fopen(OutputPath, "w");
    if (!f) {
        return E_FAIL;
    }

    fprintf(f, "# ANXCONFIG Generated Autoconf Fragment\n");
    fprintf(f, "# This file is automatically generated. DO NOT EDIT.\n");
    fprintf(f, "\n");
    fprintf(f, "AC_DEFINE([CONFIG_EXAMPLE], [1], [Example configuration])\n");
    fprintf(f, "\n");

    fclose(f);
    return S_OK;
}

/* Vtable */
static CONST IConfigGenerator_Vtbl GeneratorVtbl = {
    Generator_QueryInterface,
    Generator_AddRef,
    Generator_Release,
    Generator_GenerateCMakeCache,
    Generator_GenerateCHeader,
    Generator_GenerateMakefile,
    Generator_GenerateAutoconf
};

/* Factory function */
HRESULT ANXAPI AnxConfigCreateGenerator(OUT IConfigGenerator **Generator)
{
    ConfigGenerator *gen;

    if (Generator == NULL) {
        return E_POINTER;
    }

    gen = (ConfigGenerator *)calloc(1, sizeof(ConfigGenerator));
    if (gen == NULL) {
        *Generator = NULL;
        return E_OUTOFMEMORY;
    }

    gen->Interface.Vtbl = &GeneratorVtbl;
    gen->RefCount = 1;

    *Generator = &gen->Interface;
    return S_OK;
}
