name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++ gcc-riscv64-linux-gnu

      - name: Build for x86/x64
        run: |
          make build

      - name: Build for RISCV64
        run: |
          make build-riscv64